### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/developers#14]
There is a [License field in package.json](https://github.com/windingtree/docs/blob/master/package.json#L25) but there is no LICENSE file.

- [x] license files @kvbik 
- [x] license content footers @JirkaChadima  
- [ ] license paragraph to README @netmilk

**Comment by kvbik** [comment]
for the code we will use `apache20`, for content `cc-by-sa-40` and for code snippets `cc0`.

we will need footer for all the pages and license files for the repo (pr will follow).

inspired by https://github.com/pyvec/naucse.python.cz/ - kudos to the python community efforts!

**Comment by JirkaChadima** [comment]
Resource: Multi licensing in npm's `package.json` file - https://docs.npmjs.com/files/package.json#license

I would go with `{"license": "SEE LICENSE IN LICENSE"}` as the `OR` syntax does not seem expressive enough to me.

**Comment by JirkaChadima** [comment]
I've started the work in feat/license branch or PR #27

**Comment by kvbik** [comment]
pushed the license files. feel free to reorganise it...

**Comment by netmilk** [comment]
Closing #27
