### ISSUE TITLE
Prefer HTTPs over Swarm

### ISSUE THREAD

**Issue by czervenka** [windingtree/developers#32]
Swarm is not reliable enough to use it as default storage. Let's change documentation to recomend HTTPs.

**Comment by JirkaChadima** [comment]
Where exactly? There's a [whole page](https://developers.windingtree.com/tutorials/how-to-pick-off-chain-storage.html) on picking off-chain storage. In other tutorials, Swarm is used because if you use it, you don't have to setup HTTPS storage by yourself and the tooling support is somewhat limited for HTTPS

**Comment by czervenka** [comment]
I don't know. When a developer wants to start using Winding Tree he/she should not be instructed to use Swarm as it is not ready yet. Find the right places is part of the issue.

**Comment by czervenka** [comment]
[How to setup write API](https://developers.windingtree.com/tutorials/how-to-setup-write-api.html) (because step by step tutorial links here), [How to pick an appropriate off-chain storage](https://developers.windingtree.com/tutorials/how-to-pick-off-chain-storage.html) - remove Swarm (it is an advanced option not ready for real use), probably other places ... @netmilk can help?

**Comment by JirkaChadima** [comment]
If we remove Swarm from How to pick an appropriate off-chain storage, then the page doesn't make any sense, because you are left with a single option.

**Comment by czervenka** [comment]
You are right. It could make sense to create an advanced article with title "Hacking: How to experiment with Swarm".

**Comment by JirkaChadima** [comment]
Today, I got an idea. We can use http://pastebin.com, https://jsonblob.com or any other online snippet sharing service as the simplest public HTTP storage. With that we can easily write a tutorial that uses write api but does not use swarm or S3.

**Comment by czervenka** [comment]
I like the idea a lot. Let's do it.

**Comment by JirkaChadima** [comment]
Handled in #47
