### ISSUE TITLE
ORG.JSON Specification Update

### ISSUE THREAD

**Issue by kvakes** [windingtree/developers#55]
It has to reflect this:

Apart from the meta-fields (`dataFormatVersion` and `updatedAt`), you must have at least one of the following fields in your ORG.JSON: `legalEntity`, `hotel`, `airline`, `ota` (the last three fields correspondent to the Segment Directories that we have created so far). Here are some valid ORG.JSON examples.

**Comment by JirkaChadima** [comment]
Why should it be possible to have an organization without legalEntity? What's the point of that?

**Comment by kvakes** [comment]
In one of our discussions about ORG.ID, we imagined a structure where a few different hotels would be operated by one legal entity. All those hotels would be represented by their respective ORG.IDs and the umbrella legal entity would have its own separate ORG.ID record.

**Comment by JirkaChadima** [comment]
Yes, but there is no way of connecting the umbrella entity to its children *without* some kind of relationship. Apart from showing `legalEntity` as data, it is possible to represent it as a signed link to another ORG.ID, but it has to be present.

**Comment by kvakes** [comment]
Agreed. Let's develop these ideas further. I'll update the docs to reflect the status quo.

**Comment by JirkaChadima** [comment]
Cool. It's already in the data specs. Closing this one.
